import Head from "next/head";
import dynamic from "next/dynamic";
// import { MdSearch } from "react-icons/md";
// import { IoMdClose } from "react-icons/io";

const Header = dynamic(() => import("../components/homepagecomponents/Header"));
const Settings = dynamic(() => import("../components/settings"));
const Body = dynamic(() => import("../components/homepagecomponents/Body"));
const Footer = dynamic(() => import("../components/homepagecomponents/Footer"));

export default function Home() {
	return (
		<div className="flex flex-col justify-between h-screen font-sans md:overflow-x-scroll">
			<Head>
				<title>Google clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* header */}
			<Header />

			{/* body */}

			<Body />

			<Settings />

			{/* footer */}
			<Footer />
		</div>
	);
}
