import Head from "next/head";
import Image from "next/image";

import { MdSearch } from "react-icons/md";
import { IoMdClose } from "react-icons/io";

const search = () => {
	return (
		<div>
			<Head>
				<title>Search Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* header */}

			<header>
				<div>
					<div className="h-32">
						<Image
							src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
							alt="google image"
							width={120}
							height={40}
						/>
						<form className=" flex justify-between items-center border border-gray-200 rounded-full px-5 py-2 h-16 w-5/12 hover:shadow-md focus-within:shadow-md">
							<MdSearch className="text-2xl text-gray-400 mr-2" />

							<input
								// ref={searchInputRef}
								className=" w-100 text-xl text-gray-700 focus:outline-none mr-2"
								type="text"
							/>

							<IoMdClose
								className="text-5xl h-9 text-gray-500 flex items-center -mr-1
						    pr-4 border-r"
							/>

							<svg
								className="h-7"
								focusable="false"
								viewBox="0 0 24 24"
								xmlns="http://www.w3.org/2000/svg"
							>
								<path
									d="m12 15c1.66 0 3-1.31 3-2.97v-7.02c0-1.66-1.34-3.01-3-3.01s-3 1.34-3 3.01v7.02c0 1.66 1.34 2.97 3 2.97z"
									fill="#4285f4"
								></path>
								<path d="m11 18.08h2v3.92h-2z" fill="#34a853"></path>
								<path
									d="m7.05 16.87c-1.27-1.33-2.05-2.83-2.05-4.87h2c0 1.45 0.56 2.42 1.47 3.38v0.32l-1.15 1.18z"
									fill="#f4b400"
								></path>
								<path
									d="m12 16.93a4.97 5.25 0 0 1 -3.54 -1.55l-1.41 1.49c1.26 1.34 3.02 2.13 4.95 2.13 3.87 0 6.99-2.92 6.99-7h-1.99c0 2.92-2.24 4.93-5 4.93z"
									fill="#ea4335"
								></path>
							</svg>
						</form>
					</div>
				</div>
				<div></div>
			</header>
		</div>
	);
};

export default search;
